title: <center>You-Wei Luo</center> <br> <center>Lavie</center> <br> <center>罗又维</center>
logo: photograph.jpg
description: <link rel="stylesheet" href="./css1/myicon/iconfont.css"> <i class="fa fa-graduation-cap" aria-hidden="true"></i> Ph.D. candidate <br> School of Mathematics <br> <a href="http://www.sysu.edu.cn/en/index.htm">Sun Yat-Sen University</a> <br> <a href="https://scholar.google.com.hk/citations?user=n9xRWGsAAAAJ&hl=en&oi=sra">Google Scholar</a> <br> <a href="https://www.semanticscholar.org/author/You-Wei-Luo/120198052">Semantic Scholar</a> <br> luoyw28@mail2.sysu.edu.cn
show_downloads: false
google_analytics: UA-176789770-1
theme: jekyll-theme-minimal
github.is_project_page: false
