title: <center>You-Wei Luo</center> <br> <center>Lavie</center> <br> <center>罗又维</center>
logo: /assets/img/logo.png
description: Ph.D. candidate <br> School of Mathematics <br> <a href="http://www.sysu.edu.cn/en/index.htm">Sun Yat-Sen University</a> <br> <a href="https://scholar.google.com.hk/citations?user=n9xRWGsAAAAJ&hl=en&oi=sra">Google Scholar</a> <br> luoyw28@mail2.sysu.edu.cn
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
